// Code generated by internal/api/gen from local.go; DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"time"

	"github.com/localroot4/deyroute/internal/state"
)

// Compile-time check that the generated client implements Local.
var _ Local = (*localClient)(nil)

// Status implements Local.Status by calling the daemon over the unix socket.
func (c *localClient) Status(ctx context.Context) (Status, error) {
	var out Status
	err := c.call(ctx, "Status", nil, &out)
	return out, err
}

// Events implements Local.Events by calling the daemon over the unix socket.
func (c *localClient) Events(ctx context.Context, q EventQuery) ([]state.Event, error) {
	var out []state.Event
	err := c.call(ctx, "Events", []any{q}, &out)
	return out, err
}

// Logs implements Local.Logs by calling the daemon over the unix socket.
func (c *localClient) Logs(ctx context.Context, q LogQuery, emit func(LogLine) error) error {
	return c.stream(ctx, "Logs", []any{q}, nil, nil, emit)
}

// ConfigApply implements Local.ConfigApply by calling the daemon over the unix socket.
func (c *localClient) ConfigApply(ctx context.Context, progress func(Step)) (ApplyResult, error) {
	var out ApplyResult
	err := c.stream(ctx, "ConfigApply", nil, &out, progress, nil)
	return out, err
}

// SettingsSet implements Local.SettingsSet by calling the daemon over the unix socket.
func (c *localClient) SettingsSet(ctx context.Context, req SettingsRequest) error {
	return c.call(ctx, "SettingsSet", []any{req}, nil)
}

// NodeJoinCommand implements Local.NodeJoinCommand by calling the daemon over the unix socket.
func (c *localClient) NodeJoinCommand(ctx context.Context, ttl time.Duration) (JoinCommand, error) {
	var out JoinCommand
	err := c.call(ctx, "NodeJoinCommand", []any{ttl}, &out)
	return out, err
}

// NodeList implements Local.NodeList by calling the daemon over the unix socket.
func (c *localClient) NodeList(ctx context.Context) ([]NodeInfo, error) {
	var out []NodeInfo
	err := c.call(ctx, "NodeList", nil, &out)
	return out, err
}

// NodeRename implements Local.NodeRename by calling the daemon over the unix socket.
func (c *localClient) NodeRename(ctx context.Context, id string, name string) error {
	return c.call(ctx, "NodeRename", []any{id, name}, nil)
}

// NodeRemove implements Local.NodeRemove by calling the daemon over the unix socket.
func (c *localClient) NodeRemove(ctx context.Context, id string) error {
	return c.call(ctx, "NodeRemove", []any{id}, nil)
}

// NodeTest implements Local.NodeTest by calling the daemon over the unix socket.
func (c *localClient) NodeTest(ctx context.Context, id string) (NodeTestResult, error) {
	var out NodeTestResult
	err := c.call(ctx, "NodeTest", []any{id}, &out)
	return out, err
}

// HubAnnounceMove implements Local.HubAnnounceMove by calling the daemon over the unix socket.
func (c *localClient) HubAnnounceMove(ctx context.Context, newAddr string) (AnnounceResult, error) {
	var out AnnounceResult
	err := c.call(ctx, "HubAnnounceMove", []any{newAddr}, &out)
	return out, err
}

// NodeSetHub implements Local.NodeSetHub by calling the daemon over the unix socket.
func (c *localClient) NodeSetHub(ctx context.Context, addr string) error {
	return c.call(ctx, "NodeSetHub", []any{addr}, nil)
}

// TunnelAdd implements Local.TunnelAdd by calling the daemon over the unix socket.
func (c *localClient) TunnelAdd(ctx context.Context, req TunnelAddRequest, progress func(Step)) (TunnelInfo, error) {
	var out TunnelInfo
	err := c.stream(ctx, "TunnelAdd", []any{req}, &out, progress, nil)
	return out, err
}

// TunnelList implements Local.TunnelList by calling the daemon over the unix socket.
func (c *localClient) TunnelList(ctx context.Context) ([]TunnelInfo, error) {
	var out []TunnelInfo
	err := c.call(ctx, "TunnelList", nil, &out)
	return out, err
}

// TunnelShow implements Local.TunnelShow by calling the daemon over the unix socket.
func (c *localClient) TunnelShow(ctx context.Context, id string) (TunnelDetail, error) {
	var out TunnelDetail
	err := c.call(ctx, "TunnelShow", []any{id}, &out)
	return out, err
}

// TunnelEdit implements Local.TunnelEdit by calling the daemon over the unix socket.
func (c *localClient) TunnelEdit(ctx context.Context, id string, req TunnelEditRequest, progress func(Step)) (TunnelInfo, error) {
	var out TunnelInfo
	err := c.stream(ctx, "TunnelEdit", []any{id, req}, &out, progress, nil)
	return out, err
}

// TunnelSetEnabled implements Local.TunnelSetEnabled by calling the daemon over the unix socket.
func (c *localClient) TunnelSetEnabled(ctx context.Context, id string, enabled bool) error {
	return c.call(ctx, "TunnelSetEnabled", []any{id, enabled}, nil)
}

// TunnelRestart implements Local.TunnelRestart by calling the daemon over the unix socket.
func (c *localClient) TunnelRestart(ctx context.Context, id string) error {
	return c.call(ctx, "TunnelRestart", []any{id}, nil)
}

// TunnelDelete implements Local.TunnelDelete by calling the daemon over the unix socket.
func (c *localClient) TunnelDelete(ctx context.Context, id string, progress func(Step)) error {
	return c.stream(ctx, "TunnelDelete", []any{id}, nil, progress, nil)
}

// TunnelSwitch implements Local.TunnelSwitch by calling the daemon over the unix socket.
func (c *localClient) TunnelSwitch(ctx context.Context, id string, req SwitchRequest) error {
	return c.call(ctx, "TunnelSwitch", []any{id, req}, nil)
}

// TunnelReset implements Local.TunnelReset by calling the daemon over the unix socket.
func (c *localClient) TunnelReset(ctx context.Context, id string) error {
	return c.call(ctx, "TunnelReset", []any{id}, nil)
}

// TunnelPause implements Local.TunnelPause by calling the daemon over the unix socket.
func (c *localClient) TunnelPause(ctx context.Context, id string) error {
	return c.call(ctx, "TunnelPause", []any{id}, nil)
}

// TunnelResume implements Local.TunnelResume by calling the daemon over the unix socket.
func (c *localClient) TunnelResume(ctx context.Context, id string) error {
	return c.call(ctx, "TunnelResume", []any{id}, nil)
}

// TunnelTestLadder implements Local.TunnelTestLadder by calling the daemon over the unix socket.
func (c *localClient) TunnelTestLadder(ctx context.Context, id string, progress func(Step)) ([]RungResult, error) {
	var out []RungResult
	err := c.stream(ctx, "TunnelTestLadder", []any{id}, &out, progress, nil)
	return out, err
}

// TunnelBackupAdd implements Local.TunnelBackupAdd by calling the daemon over the unix socket.
func (c *localClient) TunnelBackupAdd(ctx context.Context, id string, node string, progress func(Step)) error {
	return c.stream(ctx, "TunnelBackupAdd", []any{id, node}, nil, progress, nil)
}

// TunnelBackupRemove implements Local.TunnelBackupRemove by calling the daemon over the unix socket.
func (c *localClient) TunnelBackupRemove(ctx context.Context, id string, node string) error {
	return c.call(ctx, "TunnelBackupRemove", []any{id, node}, nil)
}

// PortAdd implements Local.PortAdd by calling the daemon over the unix socket.
func (c *localClient) PortAdd(ctx context.Context, tunnel string, specs []PortSpec, progress func(Step)) (TunnelInfo, error) {
	var out TunnelInfo
	err := c.stream(ctx, "PortAdd", []any{tunnel, specs}, &out, progress, nil)
	return out, err
}

// PortRemove implements Local.PortRemove by calling the daemon over the unix socket.
func (c *localClient) PortRemove(ctx context.Context, tunnel string, listen int, proto string) (TunnelInfo, error) {
	var out TunnelInfo
	err := c.call(ctx, "PortRemove", []any{tunnel, listen, proto}, &out)
	return out, err
}

// PortCheck implements Local.PortCheck by calling the daemon over the unix socket.
func (c *localClient) PortCheck(ctx context.Context, req PortCheckRequest) (PortCheckResult, error) {
	var out PortCheckResult
	err := c.call(ctx, "PortCheck", []any{req}, &out)
	return out, err
}

// PortSuggest implements Local.PortSuggest by calling the daemon over the unix socket.
func (c *localClient) PortSuggest(ctx context.Context, count int) ([]int, error) {
	var out []int
	err := c.call(ctx, "PortSuggest", []any{count}, &out)
	return out, err
}

// LadderList implements Local.LadderList by calling the daemon over the unix socket.
func (c *localClient) LadderList(ctx context.Context) ([]Ladder, error) {
	var out []Ladder
	err := c.call(ctx, "LadderList", nil, &out)
	return out, err
}

// LadderSave implements Local.LadderSave by calling the daemon over the unix socket.
func (c *localClient) LadderSave(ctx context.Context, name string, rungs []string, create bool) error {
	return c.call(ctx, "LadderSave", []any{name, rungs, create}, nil)
}

// LadderDelete implements Local.LadderDelete by calling the daemon over the unix socket.
func (c *localClient) LadderDelete(ctx context.Context, name string) error {
	return c.call(ctx, "LadderDelete", []any{name}, nil)
}

// TransportList implements Local.TransportList by calling the daemon over the unix socket.
func (c *localClient) TransportList(ctx context.Context) ([]TransportInfo, error) {
	var out []TransportInfo
	err := c.call(ctx, "TransportList", nil, &out)
	return out, err
}

// DiagSpeed implements Local.DiagSpeed by calling the daemon over the unix socket.
func (c *localClient) DiagSpeed(ctx context.Context, tunnel string, seconds int, progress func(Step)) (SpeedResult, error) {
	var out SpeedResult
	err := c.stream(ctx, "DiagSpeed", []any{tunnel, seconds}, &out, progress, nil)
	return out, err
}

// DiagProbe implements Local.DiagProbe by calling the daemon over the unix socket.
func (c *localClient) DiagProbe(ctx context.Context, tunnel string, allPorts bool) ([]ProbeReport, error) {
	var out []ProbeReport
	err := c.call(ctx, "DiagProbe", []any{tunnel, allPorts}, &out)
	return out, err
}

// DoctorCollect implements Local.DoctorCollect by calling the daemon over the unix socket.
func (c *localClient) DoctorCollect(ctx context.Context, node string) (DoctorData, error) {
	var out DoctorData
	err := c.call(ctx, "DoctorCollect", []any{node}, &out)
	return out, err
}

// OptimizeStatus implements Local.OptimizeStatus by calling the daemon over the unix socket.
func (c *localClient) OptimizeStatus(ctx context.Context) (OptimizeStatus, error) {
	var out OptimizeStatus
	err := c.call(ctx, "OptimizeStatus", nil, &out)
	return out, err
}

// OptimizeApply implements Local.OptimizeApply by calling the daemon over the unix socket.
func (c *localClient) OptimizeApply(ctx context.Context, profile string) (OptimizeStatus, error) {
	var out OptimizeStatus
	err := c.call(ctx, "OptimizeApply", []any{profile}, &out)
	return out, err
}

// OptimizeRevert implements Local.OptimizeRevert by calling the daemon over the unix socket.
func (c *localClient) OptimizeRevert(ctx context.Context) (OptimizeStatus, error) {
	var out OptimizeStatus
	err := c.call(ctx, "OptimizeRevert", nil, &out)
	return out, err
}

// SecurityRotateTokens implements Local.SecurityRotateTokens by calling the daemon over the unix socket.
func (c *localClient) SecurityRotateTokens(ctx context.Context, tunnel string, progress func(Step)) error {
	return c.stream(ctx, "SecurityRotateTokens", []any{tunnel}, nil, progress, nil)
}

// SecurityRotateCA implements Local.SecurityRotateCA by calling the daemon over the unix socket.
func (c *localClient) SecurityRotateCA(ctx context.Context, progress func(Step)) (RotateCAResult, error) {
	var out RotateCAResult
	err := c.stream(ctx, "SecurityRotateCA", nil, &out, progress, nil)
	return out, err
}

// SecurityTLSShow implements Local.SecurityTLSShow by calling the daemon over the unix socket.
func (c *localClient) SecurityTLSShow(ctx context.Context, tunnel string) ([]CertInfo, error) {
	var out []CertInfo
	err := c.call(ctx, "SecurityTLSShow", []any{tunnel}, &out)
	return out, err
}

// SecurityTLSRenew implements Local.SecurityTLSRenew by calling the daemon over the unix socket.
func (c *localClient) SecurityTLSRenew(ctx context.Context, tunnel string) ([]CertInfo, error) {
	var out []CertInfo
	err := c.call(ctx, "SecurityTLSRenew", []any{tunnel}, &out)
	return out, err
}

// SecurityFirewall implements Local.SecurityFirewall by calling the daemon over the unix socket.
func (c *localClient) SecurityFirewall(ctx context.Context, action string) (FirewallInfo, error) {
	var out FirewallInfo
	err := c.call(ctx, "SecurityFirewall", []any{action}, &out)
	return out, err
}

// SecurityAudit implements Local.SecurityAudit by calling the daemon over the unix socket.
func (c *localClient) SecurityAudit(ctx context.Context) (AuditReport, error) {
	var out AuditReport
	err := c.call(ctx, "SecurityAudit", nil, &out)
	return out, err
}

// NotifyTelegramSet implements Local.NotifyTelegramSet by calling the daemon over the unix socket.
func (c *localClient) NotifyTelegramSet(ctx context.Context, tokenFile string, chatID string, events []string) error {
	return c.call(ctx, "NotifyTelegramSet", []any{tokenFile, chatID, events}, nil)
}

// NotifyTelegramTest implements Local.NotifyTelegramTest by calling the daemon over the unix socket.
func (c *localClient) NotifyTelegramTest(ctx context.Context) error {
	return c.call(ctx, "NotifyTelegramTest", nil, nil)
}

// NotifyTelegramOff implements Local.NotifyTelegramOff by calling the daemon over the unix socket.
func (c *localClient) NotifyTelegramOff(ctx context.Context) error {
	return c.call(ctx, "NotifyTelegramOff", nil, nil)
}

// UpdateCheck implements Local.UpdateCheck by calling the daemon over the unix socket.
func (c *localClient) UpdateCheck(ctx context.Context) (UpdateInfo, error) {
	var out UpdateInfo
	err := c.call(ctx, "UpdateCheck", nil, &out)
	return out, err
}

// UpdateApply implements Local.UpdateApply by calling the daemon over the unix socket.
func (c *localClient) UpdateApply(ctx context.Context, version string, progress func(Step)) (UpdateInfo, error) {
	var out UpdateInfo
	err := c.stream(ctx, "UpdateApply", []any{version}, &out, progress, nil)
	return out, err
}

// UpdateRollback implements Local.UpdateRollback by calling the daemon over the unix socket.
func (c *localClient) UpdateRollback(ctx context.Context) (UpdateInfo, error) {
	var out UpdateInfo
	err := c.call(ctx, "UpdateRollback", nil, &out)
	return out, err
}

// UpdateBackends implements Local.UpdateBackends by calling the daemon over the unix socket.
func (c *localClient) UpdateBackends(ctx context.Context, name string, progress func(Step)) ([]BackendUpdate, error) {
	var out []BackendUpdate
	err := c.stream(ctx, "UpdateBackends", []any{name}, &out, progress, nil)
	return out, err
}

// UpdateManifest implements Local.UpdateManifest by calling the daemon over the unix socket.
func (c *localClient) UpdateManifest(ctx context.Context) (ManifestInfo, error) {
	var out ManifestInfo
	err := c.call(ctx, "UpdateManifest", nil, &out)
	return out, err
}

// UninstallNodes implements Local.UninstallNodes by calling the daemon over the unix socket.
func (c *localClient) UninstallNodes(ctx context.Context) ([]string, error) {
	var out []string
	err := c.call(ctx, "UninstallNodes", nil, &out)
	return out, err
}

// StopAll implements Local.StopAll by calling the daemon over the unix socket.
func (c *localClient) StopAll(ctx context.Context) error {
	return c.call(ctx, "StopAll", nil, nil)
}

// NewLocalHandler returns the HTTP handler that serves impl on
// POST /v1/rpc/<Method> (see ARCHITECTURE.md section 6). Panics in impl are
// recovered, logged with their stack and answered with DEY-X000.
func NewLocalHandler(impl Local, logger *slog.Logger) http.Handler {
	return newRPCHandler(logger, map[string]rpcMethod{
		"Status": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.Status(ctx)
		}},
		"Events": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 EventQuery
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.Events(ctx, a0)
		}},
		"Logs": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 LogQuery
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.Logs(ctx, a0, cb.Log)
		}},
		"ConfigApply": {arity: 0, stream: true, call: func(ctx context.Context, _ []json.RawMessage, cb *rpcCallbacks) (any, error) {
			return impl.ConfigApply(ctx, cb.Step)
		}},
		"SettingsSet": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 SettingsRequest
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.SettingsSet(ctx, a0)
		}},
		"NodeJoinCommand": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 time.Duration
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.NodeJoinCommand(ctx, a0)
		}},
		"NodeList": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.NodeList(ctx)
		}},
		"NodeRename": {arity: 2, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 string
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return nil, impl.NodeRename(ctx, a0, a1)
		}},
		"NodeRemove": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.NodeRemove(ctx, a0)
		}},
		"NodeTest": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.NodeTest(ctx, a0)
		}},
		"HubAnnounceMove": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.HubAnnounceMove(ctx, a0)
		}},
		"NodeSetHub": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.NodeSetHub(ctx, a0)
		}},
		"TunnelAdd": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 TunnelAddRequest
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.TunnelAdd(ctx, a0, cb.Step)
		}},
		"TunnelList": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.TunnelList(ctx)
		}},
		"TunnelShow": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.TunnelShow(ctx, a0)
		}},
		"TunnelEdit": {arity: 2, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 TunnelEditRequest
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return impl.TunnelEdit(ctx, a0, a1, cb.Step)
		}},
		"TunnelSetEnabled": {arity: 2, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 bool
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return nil, impl.TunnelSetEnabled(ctx, a0, a1)
		}},
		"TunnelRestart": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.TunnelRestart(ctx, a0)
		}},
		"TunnelDelete": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.TunnelDelete(ctx, a0, cb.Step)
		}},
		"TunnelSwitch": {arity: 2, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 SwitchRequest
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return nil, impl.TunnelSwitch(ctx, a0, a1)
		}},
		"TunnelReset": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.TunnelReset(ctx, a0)
		}},
		"TunnelPause": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.TunnelPause(ctx, a0)
		}},
		"TunnelResume": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.TunnelResume(ctx, a0)
		}},
		"TunnelTestLadder": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.TunnelTestLadder(ctx, a0, cb.Step)
		}},
		"TunnelBackupAdd": {arity: 2, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 string
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return nil, impl.TunnelBackupAdd(ctx, a0, a1, cb.Step)
		}},
		"TunnelBackupRemove": {arity: 2, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 string
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return nil, impl.TunnelBackupRemove(ctx, a0, a1)
		}},
		"PortAdd": {arity: 2, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 []PortSpec
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return impl.PortAdd(ctx, a0, a1, cb.Step)
		}},
		"PortRemove": {arity: 3, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 int
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			var a2 string
			if err := decodeArg(args, 2, &a2); err != nil {
				return nil, err
			}
			return impl.PortRemove(ctx, a0, a1, a2)
		}},
		"PortCheck": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 PortCheckRequest
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.PortCheck(ctx, a0)
		}},
		"PortSuggest": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 int
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.PortSuggest(ctx, a0)
		}},
		"LadderList": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.LadderList(ctx)
		}},
		"LadderSave": {arity: 3, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 []string
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			var a2 bool
			if err := decodeArg(args, 2, &a2); err != nil {
				return nil, err
			}
			return nil, impl.LadderSave(ctx, a0, a1, a2)
		}},
		"LadderDelete": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.LadderDelete(ctx, a0)
		}},
		"TransportList": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.TransportList(ctx)
		}},
		"DiagSpeed": {arity: 2, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 int
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return impl.DiagSpeed(ctx, a0, a1, cb.Step)
		}},
		"DiagProbe": {arity: 2, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 bool
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			return impl.DiagProbe(ctx, a0, a1)
		}},
		"DoctorCollect": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.DoctorCollect(ctx, a0)
		}},
		"OptimizeStatus": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.OptimizeStatus(ctx)
		}},
		"OptimizeApply": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.OptimizeApply(ctx, a0)
		}},
		"OptimizeRevert": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.OptimizeRevert(ctx)
		}},
		"SecurityRotateTokens": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return nil, impl.SecurityRotateTokens(ctx, a0, cb.Step)
		}},
		"SecurityRotateCA": {arity: 0, stream: true, call: func(ctx context.Context, _ []json.RawMessage, cb *rpcCallbacks) (any, error) {
			return impl.SecurityRotateCA(ctx, cb.Step)
		}},
		"SecurityTLSShow": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.SecurityTLSShow(ctx, a0)
		}},
		"SecurityTLSRenew": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.SecurityTLSRenew(ctx, a0)
		}},
		"SecurityFirewall": {arity: 1, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.SecurityFirewall(ctx, a0)
		}},
		"SecurityAudit": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.SecurityAudit(ctx)
		}},
		"NotifyTelegramSet": {arity: 3, stream: false, call: func(ctx context.Context, args []json.RawMessage, _ *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			var a1 string
			if err := decodeArg(args, 1, &a1); err != nil {
				return nil, err
			}
			var a2 []string
			if err := decodeArg(args, 2, &a2); err != nil {
				return nil, err
			}
			return nil, impl.NotifyTelegramSet(ctx, a0, a1, a2)
		}},
		"NotifyTelegramTest": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return nil, impl.NotifyTelegramTest(ctx)
		}},
		"NotifyTelegramOff": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return nil, impl.NotifyTelegramOff(ctx)
		}},
		"UpdateCheck": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.UpdateCheck(ctx)
		}},
		"UpdateApply": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.UpdateApply(ctx, a0, cb.Step)
		}},
		"UpdateRollback": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.UpdateRollback(ctx)
		}},
		"UpdateBackends": {arity: 1, stream: true, call: func(ctx context.Context, args []json.RawMessage, cb *rpcCallbacks) (any, error) {
			var a0 string
			if err := decodeArg(args, 0, &a0); err != nil {
				return nil, err
			}
			return impl.UpdateBackends(ctx, a0, cb.Step)
		}},
		"UpdateManifest": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.UpdateManifest(ctx)
		}},
		"UninstallNodes": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return impl.UninstallNodes(ctx)
		}},
		"StopAll": {arity: 0, stream: false, call: func(ctx context.Context, _ []json.RawMessage, _ *rpcCallbacks) (any, error) {
			return nil, impl.StopAll(ctx)
		}},
	})
}
