// Code generated by internal/api/gen from local.go; DO NOT EDIT.

package api

import (
	"context"
	"time"

	deyerr "github.com/localroot4/deyroute/internal/errors"
	"github.com/localroot4/deyroute/internal/state"
)

// UnimplementedLocal implements Local by answering DEY-X009 ("this command
// needs a <Need>, but this server is a <Role>") for every method. A daemon
// embeds it and overrides the methods its role serves, e.g.
//
//	type nodeLocal struct{ api.UnimplementedLocal }
//
//	l := &nodeLocal{UnimplementedLocal: api.UnimplementedLocal{Role: "node", Need: "hub"}}
type UnimplementedLocal struct {
	// Role is the role of this server (hub or node).
	Role string
	// Need is the role the unimplemented methods require.
	Need string
}

// Compile-time check that UnimplementedLocal implements Local.
var _ Local = UnimplementedLocal{}

// wrongRole is the DEY-X009 error every method returns.
func (u UnimplementedLocal) wrongRole() error {
	return deyerr.New(deyerr.X009, deyerr.Params{"role": u.Role, "need": u.Need})
}

// Status implements Local.Status; it returns DEY-X009.
func (u UnimplementedLocal) Status(ctx context.Context) (Status, error) {
	var zero Status
	return zero, u.wrongRole()
}

// Events implements Local.Events; it returns DEY-X009.
func (u UnimplementedLocal) Events(ctx context.Context, q EventQuery) ([]state.Event, error) {
	var zero []state.Event
	return zero, u.wrongRole()
}

// Logs implements Local.Logs; it returns DEY-X009.
func (u UnimplementedLocal) Logs(ctx context.Context, q LogQuery, emit func(LogLine) error) error {
	return u.wrongRole()
}

// ConfigApply implements Local.ConfigApply; it returns DEY-X009.
func (u UnimplementedLocal) ConfigApply(ctx context.Context, progress func(Step)) (ApplyResult, error) {
	var zero ApplyResult
	return zero, u.wrongRole()
}

// SettingsSet implements Local.SettingsSet; it returns DEY-X009.
func (u UnimplementedLocal) SettingsSet(ctx context.Context, req SettingsRequest) error {
	return u.wrongRole()
}

// NodeJoinCommand implements Local.NodeJoinCommand; it returns DEY-X009.
func (u UnimplementedLocal) NodeJoinCommand(ctx context.Context, ttl time.Duration) (JoinCommand, error) {
	var zero JoinCommand
	return zero, u.wrongRole()
}

// NodeList implements Local.NodeList; it returns DEY-X009.
func (u UnimplementedLocal) NodeList(ctx context.Context) ([]NodeInfo, error) {
	var zero []NodeInfo
	return zero, u.wrongRole()
}

// NodeRename implements Local.NodeRename; it returns DEY-X009.
func (u UnimplementedLocal) NodeRename(ctx context.Context, id string, name string) error {
	return u.wrongRole()
}

// NodeRemove implements Local.NodeRemove; it returns DEY-X009.
func (u UnimplementedLocal) NodeRemove(ctx context.Context, id string) error {
	return u.wrongRole()
}

// NodeTest implements Local.NodeTest; it returns DEY-X009.
func (u UnimplementedLocal) NodeTest(ctx context.Context, id string) (NodeTestResult, error) {
	var zero NodeTestResult
	return zero, u.wrongRole()
}

// HubAnnounceMove implements Local.HubAnnounceMove; it returns DEY-X009.
func (u UnimplementedLocal) HubAnnounceMove(ctx context.Context, newAddr string) (AnnounceResult, error) {
	var zero AnnounceResult
	return zero, u.wrongRole()
}

// NodeSetHub implements Local.NodeSetHub; it returns DEY-X009.
func (u UnimplementedLocal) NodeSetHub(ctx context.Context, addr string) error {
	return u.wrongRole()
}

// TunnelAdd implements Local.TunnelAdd; it returns DEY-X009.
func (u UnimplementedLocal) TunnelAdd(ctx context.Context, req TunnelAddRequest, progress func(Step)) (TunnelInfo, error) {
	var zero TunnelInfo
	return zero, u.wrongRole()
}

// TunnelList implements Local.TunnelList; it returns DEY-X009.
func (u UnimplementedLocal) TunnelList(ctx context.Context) ([]TunnelInfo, error) {
	var zero []TunnelInfo
	return zero, u.wrongRole()
}

// TunnelShow implements Local.TunnelShow; it returns DEY-X009.
func (u UnimplementedLocal) TunnelShow(ctx context.Context, id string) (TunnelDetail, error) {
	var zero TunnelDetail
	return zero, u.wrongRole()
}

// TunnelEdit implements Local.TunnelEdit; it returns DEY-X009.
func (u UnimplementedLocal) TunnelEdit(ctx context.Context, id string, req TunnelEditRequest, progress func(Step)) (TunnelInfo, error) {
	var zero TunnelInfo
	return zero, u.wrongRole()
}

// TunnelSetEnabled implements Local.TunnelSetEnabled; it returns DEY-X009.
func (u UnimplementedLocal) TunnelSetEnabled(ctx context.Context, id string, enabled bool) error {
	return u.wrongRole()
}

// TunnelRestart implements Local.TunnelRestart; it returns DEY-X009.
func (u UnimplementedLocal) TunnelRestart(ctx context.Context, id string) error {
	return u.wrongRole()
}

// TunnelDelete implements Local.TunnelDelete; it returns DEY-X009.
func (u UnimplementedLocal) TunnelDelete(ctx context.Context, id string, progress func(Step)) error {
	return u.wrongRole()
}

// TunnelSwitch implements Local.TunnelSwitch; it returns DEY-X009.
func (u UnimplementedLocal) TunnelSwitch(ctx context.Context, id string, req SwitchRequest) error {
	return u.wrongRole()
}

// TunnelReset implements Local.TunnelReset; it returns DEY-X009.
func (u UnimplementedLocal) TunnelReset(ctx context.Context, id string) error {
	return u.wrongRole()
}

// TunnelPause implements Local.TunnelPause; it returns DEY-X009.
func (u UnimplementedLocal) TunnelPause(ctx context.Context, id string) error {
	return u.wrongRole()
}

// TunnelResume implements Local.TunnelResume; it returns DEY-X009.
func (u UnimplementedLocal) TunnelResume(ctx context.Context, id string) error {
	return u.wrongRole()
}

// TunnelTestLadder implements Local.TunnelTestLadder; it returns DEY-X009.
func (u UnimplementedLocal) TunnelTestLadder(ctx context.Context, id string, progress func(Step)) ([]RungResult, error) {
	var zero []RungResult
	return zero, u.wrongRole()
}

// TunnelBackupAdd implements Local.TunnelBackupAdd; it returns DEY-X009.
func (u UnimplementedLocal) TunnelBackupAdd(ctx context.Context, id string, node string, progress func(Step)) error {
	return u.wrongRole()
}

// TunnelBackupRemove implements Local.TunnelBackupRemove; it returns DEY-X009.
func (u UnimplementedLocal) TunnelBackupRemove(ctx context.Context, id string, node string) error {
	return u.wrongRole()
}

// PortAdd implements Local.PortAdd; it returns DEY-X009.
func (u UnimplementedLocal) PortAdd(ctx context.Context, tunnel string, specs []PortSpec, progress func(Step)) (TunnelInfo, error) {
	var zero TunnelInfo
	return zero, u.wrongRole()
}

// PortRemove implements Local.PortRemove; it returns DEY-X009.
func (u UnimplementedLocal) PortRemove(ctx context.Context, tunnel string, listen int, proto string) (TunnelInfo, error) {
	var zero TunnelInfo
	return zero, u.wrongRole()
}

// PortCheck implements Local.PortCheck; it returns DEY-X009.
func (u UnimplementedLocal) PortCheck(ctx context.Context, req PortCheckRequest) (PortCheckResult, error) {
	var zero PortCheckResult
	return zero, u.wrongRole()
}

// PortSuggest implements Local.PortSuggest; it returns DEY-X009.
func (u UnimplementedLocal) PortSuggest(ctx context.Context, count int) ([]int, error) {
	var zero []int
	return zero, u.wrongRole()
}

// LadderList implements Local.LadderList; it returns DEY-X009.
func (u UnimplementedLocal) LadderList(ctx context.Context) ([]Ladder, error) {
	var zero []Ladder
	return zero, u.wrongRole()
}

// LadderSave implements Local.LadderSave; it returns DEY-X009.
func (u UnimplementedLocal) LadderSave(ctx context.Context, name string, rungs []string, create bool) error {
	return u.wrongRole()
}

// LadderDelete implements Local.LadderDelete; it returns DEY-X009.
func (u UnimplementedLocal) LadderDelete(ctx context.Context, name string) error {
	return u.wrongRole()
}

// TransportList implements Local.TransportList; it returns DEY-X009.
func (u UnimplementedLocal) TransportList(ctx context.Context) ([]TransportInfo, error) {
	var zero []TransportInfo
	return zero, u.wrongRole()
}

// DiagSpeed implements Local.DiagSpeed; it returns DEY-X009.
func (u UnimplementedLocal) DiagSpeed(ctx context.Context, tunnel string, seconds int, progress func(Step)) (SpeedResult, error) {
	var zero SpeedResult
	return zero, u.wrongRole()
}

// DiagProbe implements Local.DiagProbe; it returns DEY-X009.
func (u UnimplementedLocal) DiagProbe(ctx context.Context, tunnel string, allPorts bool) ([]ProbeReport, error) {
	var zero []ProbeReport
	return zero, u.wrongRole()
}

// DoctorCollect implements Local.DoctorCollect; it returns DEY-X009.
func (u UnimplementedLocal) DoctorCollect(ctx context.Context, node string) (DoctorData, error) {
	var zero DoctorData
	return zero, u.wrongRole()
}

// OptimizeStatus implements Local.OptimizeStatus; it returns DEY-X009.
func (u UnimplementedLocal) OptimizeStatus(ctx context.Context) (OptimizeStatus, error) {
	var zero OptimizeStatus
	return zero, u.wrongRole()
}

// OptimizeApply implements Local.OptimizeApply; it returns DEY-X009.
func (u UnimplementedLocal) OptimizeApply(ctx context.Context, profile string) (OptimizeStatus, error) {
	var zero OptimizeStatus
	return zero, u.wrongRole()
}

// OptimizeRevert implements Local.OptimizeRevert; it returns DEY-X009.
func (u UnimplementedLocal) OptimizeRevert(ctx context.Context) (OptimizeStatus, error) {
	var zero OptimizeStatus
	return zero, u.wrongRole()
}

// SecurityRotateTokens implements Local.SecurityRotateTokens; it returns DEY-X009.
func (u UnimplementedLocal) SecurityRotateTokens(ctx context.Context, tunnel string, progress func(Step)) error {
	return u.wrongRole()
}

// SecurityRotateCA implements Local.SecurityRotateCA; it returns DEY-X009.
func (u UnimplementedLocal) SecurityRotateCA(ctx context.Context, progress func(Step)) (RotateCAResult, error) {
	var zero RotateCAResult
	return zero, u.wrongRole()
}

// SecurityTLSShow implements Local.SecurityTLSShow; it returns DEY-X009.
func (u UnimplementedLocal) SecurityTLSShow(ctx context.Context, tunnel string) ([]CertInfo, error) {
	var zero []CertInfo
	return zero, u.wrongRole()
}

// SecurityTLSRenew implements Local.SecurityTLSRenew; it returns DEY-X009.
func (u UnimplementedLocal) SecurityTLSRenew(ctx context.Context, tunnel string) ([]CertInfo, error) {
	var zero []CertInfo
	return zero, u.wrongRole()
}

// SecurityFirewall implements Local.SecurityFirewall; it returns DEY-X009.
func (u UnimplementedLocal) SecurityFirewall(ctx context.Context, action string) (FirewallInfo, error) {
	var zero FirewallInfo
	return zero, u.wrongRole()
}

// SecurityAudit implements Local.SecurityAudit; it returns DEY-X009.
func (u UnimplementedLocal) SecurityAudit(ctx context.Context) (AuditReport, error) {
	var zero AuditReport
	return zero, u.wrongRole()
}

// NotifyTelegramSet implements Local.NotifyTelegramSet; it returns DEY-X009.
func (u UnimplementedLocal) NotifyTelegramSet(ctx context.Context, tokenFile string, chatID string, events []string) error {
	return u.wrongRole()
}

// NotifyTelegramTest implements Local.NotifyTelegramTest; it returns DEY-X009.
func (u UnimplementedLocal) NotifyTelegramTest(ctx context.Context) error {
	return u.wrongRole()
}

// NotifyTelegramOff implements Local.NotifyTelegramOff; it returns DEY-X009.
func (u UnimplementedLocal) NotifyTelegramOff(ctx context.Context) error {
	return u.wrongRole()
}

// UpdateCheck implements Local.UpdateCheck; it returns DEY-X009.
func (u UnimplementedLocal) UpdateCheck(ctx context.Context) (UpdateInfo, error) {
	var zero UpdateInfo
	return zero, u.wrongRole()
}

// UpdateApply implements Local.UpdateApply; it returns DEY-X009.
func (u UnimplementedLocal) UpdateApply(ctx context.Context, version string, progress func(Step)) (UpdateInfo, error) {
	var zero UpdateInfo
	return zero, u.wrongRole()
}

// UpdateRollback implements Local.UpdateRollback; it returns DEY-X009.
func (u UnimplementedLocal) UpdateRollback(ctx context.Context) (UpdateInfo, error) {
	var zero UpdateInfo
	return zero, u.wrongRole()
}

// UpdateBackends implements Local.UpdateBackends; it returns DEY-X009.
func (u UnimplementedLocal) UpdateBackends(ctx context.Context, name string, progress func(Step)) ([]BackendUpdate, error) {
	var zero []BackendUpdate
	return zero, u.wrongRole()
}

// UpdateManifest implements Local.UpdateManifest; it returns DEY-X009.
func (u UnimplementedLocal) UpdateManifest(ctx context.Context) (ManifestInfo, error) {
	var zero ManifestInfo
	return zero, u.wrongRole()
}

// UninstallNodes implements Local.UninstallNodes; it returns DEY-X009.
func (u UnimplementedLocal) UninstallNodes(ctx context.Context) ([]string, error) {
	var zero []string
	return zero, u.wrongRole()
}

// StopAll implements Local.StopAll; it returns DEY-X009.
func (u UnimplementedLocal) StopAll(ctx context.Context) error {
	return u.wrongRole()
}
