package node

import (
	"context"
	"crypto/tls"
	"log/slog"
	"net"
	"net/http"
	"net/netip"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/localroot4/deyroute/internal/api"
	"github.com/localroot4/deyroute/internal/config"
	"github.com/localroot4/deyroute/internal/daemon/render"
	"github.com/localroot4/deyroute/internal/daemon/setup"
	deyerr "github.com/localroot4/deyroute/internal/errors"
	"github.com/localroot4/deyroute/internal/exec"
	"github.com/localroot4/deyroute/internal/install"
	dlog "github.com/localroot4/deyroute/internal/log"
	"github.com/localroot4/deyroute/internal/systemd"
	"github.com/localroot4/deyroute/internal/tlsutil"
	"github.com/localroot4/deyroute/internal/version"
)

// Names and files of the node agent (absolute system paths; the agent
// prefixes them with Options.Root).
const (
	// ServiceName is the node's systemd service (without ".service").
	ServiceName = "deyroute-node"
	// LogFile is the agent's own log (section 2).
	LogFile = "/var/log/deyroute/node.log"
	// CAFile is the hub CA the node trusts on the control channel.
	CAFile = "/etc/deyroute/secrets/ca.crt"
	// PendingKeyFile holds the key generated by cert.renew until the hub's
	// cert.install arrives (0600).
	PendingKeyFile = "/etc/deyroute/secrets/node.key.pending" // #nosec G101 -- file path, not a credential
	// StateFile remembers the rendered instances (config dir, backend, NAT)
	// and the hub-supplied NAT rules across agent restarts (0600).
	StateFile = "/var/lib/deyroute/node-state.json"
	// DownloadDir is where fetch.proxy and self.update stage downloads.
	DownloadDir = "/var/lib/deyroute/tmp"
)

// Defaults of the Options timings.
const (
	// DefaultReconnectDelay is how long the agent waits after answering
	// set_hub or cert.install before it drops the stream and reconnects, so
	// the answer reaches the hub over the old connection first.
	DefaultReconnectDelay = 500 * time.Millisecond
	// DefaultRestartDelay separates the answer to self.update from the
	// service restart.
	DefaultRestartDelay = time.Second
	// DefaultUninstallDelay separates the answer to uninstall from the
	// removal (section 5: reply OK, then uninstall).
	DefaultUninstallDelay = time.Second
	// DefaultStartCheckDelay is how long unit.start waits before it reads
	// the unit state, so a backend that exits at once (bad config) is
	// reported as DEY-B003 with its log instead of a later probe timeout.
	DefaultStartCheckDelay = 300 * time.Millisecond
	// DefaultFollowPoll is the poll interval of followed logs.
	DefaultFollowPoll = 500 * time.Millisecond
	// DefaultJobTimeout bounds a background job (restart, uninstall).
	DefaultJobTimeout = 5 * time.Minute
	// monitorTimeout bounds the systemctl calls of one heartbeat refresh.
	monitorTimeout = 4 * time.Second
	// DefaultStallLimit is how long the monitor may go without completing
	// a pass before the watchdog ping is withheld, so systemd restarts the
	// agent (the tunnel units keep running). A pass waits for the instance
	// lock, which a unit command holds for up to its 30-second timeout,
	// and re-runs PostStart steps of up to 30 seconds each.
	DefaultStallLimit = 90 * time.Second
)

// Options configure Run. Only Root is commonly set; every other field has
// a production default and exists so tests (and the end-to-end harness)
// run the agent unprivileged in a temporary directory.
type Options struct {
	// Root prefixes every filesystem path ("/" when empty).
	Root string
	// Runner runs allow-listed programs (systemctl, nft, ss, ip); nil =
	// exec.NewRunner().
	Runner exec.Runner
	// Logger receives the agent log; nil = internal/log writing
	// Root/var/log/deyroute/node.log (rotated, redacted).
	Logger *slog.Logger
	// Now is the clock; nil = time.Now.
	Now func() time.Time
	// SocketPath is the Local API socket; "" = Root/run/deyroute/daemon.sock.
	SocketPath string
	// HTTPClient performs downloads (backend.install, fetch.proxy) and
	// http.post; nil = a proxy-aware default client per request.
	HTTPClient *http.Client
	// Layout places backend binaries; the zero value = install.Layout{Root}.
	Layout install.Layout
	// Systemd manages units; nil = &systemd.Manager{Runner, Root}.
	Systemd *systemd.Manager
	// DeyrouteIDs returns the uid/gid of the system user deyroute (rendered
	// files are root:deyroute); nil = render.LookupDeyrouteIDs.
	DeyrouteIDs func() (uid, gid int, err error)
	// Chown changes file ownership; nil = os.Lchown.
	Chown func(path string, uid, gid int) error
	// HubAddrOverride, when set, replaces node.hub_addr from config.yaml.
	HubAddrOverride string
	// SelfBinary is the deyroute binary unit commands may run
	// ("" = /usr/local/bin/deyroute).
	SelfBinary string
	// RestartSelf restarts the agent after self.update; nil = systemctl
	// restart --no-block deyroute-node.service.
	RestartSelf func(ctx context.Context) error
	// VerifyBinary checks the binary self.update downloaded before it is
	// installed (arch is Options.Arch); nil = VerifyELF.
	VerifyBinary func(path, arch string) error
	// SetHubAddr persists a new hub target (set_hub, NodeSetHub): host:port,
	// or ws[s]://DOMAIN:PORT/SECRET for a front; nil = setup.SetHubAddr
	// (node.hub_addr and node.front in Root/etc/deyroute/config.yaml).
	SetHubAddr func(ctx context.Context, addr string) error
	// FrontDial opens the control connection through the front in front mode;
	// nil = front.DialControl (tests point it at a fake CDN with its own
	// root pool).
	FrontDial setup.FrontDialFunc
	// Uninstall removes deyroute from this server (uninstall command); nil =
	// the built-in node uninstall (units, table inet deyroute, sysctl, files,
	// then the node service itself).
	Uninstall func(ctx context.Context) error
	// Hooks run backend steps around unit start/stop; nil = BackendHooks
	// (the registered backends' PreStart/PostStart/PostStop, e.g. awg).
	Hooks Hooks
	// Mirror resolves "{mirror}" in manifest URLs ("" = $DEYROUTE_MIRROR).
	Mirror string
	// Arch is the architecture for backends and self.update
	// ("" = runtime.GOARCH).
	Arch string
	// Notify sends sd_notify states; nil = systemd.Notify.
	Notify func(state string) error
	// Getenv reads the watchdog settings systemd passes ($WATCHDOG_USEC,
	// $WATCHDOG_PID); nil = os.Getenv.
	Getenv func(key string) string
	// Listen and ListenPacket open the probe helper listeners (echo, UDP
	// echo, speed generator); nil = net.ListenConfig.
	Listen       func(ctx context.Context, network, address string) (net.Listener, error)
	ListenPacket func(ctx context.Context, network, address string) (net.PacketConn, error)
	// LocalAddrs returns this node's own addresses, the only non-loopback
	// targets a NAT rule may lead to; nil = the interface addresses.
	LocalAddrs func() ([]netip.Addr, error)

	// Timings; zero values take the defaults above and the api package's
	// (reconnect backoff 1-30 s, heartbeat 5 s).
	HeartbeatInterval      time.Duration
	BackoffMin, BackoffMax time.Duration
	ReconnectDelay         time.Duration
	RestartDelay           time.Duration
	UninstallDelay         time.Duration
	StartCheckDelay        time.Duration
	FollowPoll             time.Duration
	StallLimit             time.Duration
	// DownloadRetry tunes fetch.proxy retries (tests shorten the backoff).
	DownloadRetry install.RetryOptions
}

func (o Options) withDefaults() Options {
	if o.Root == "" {
		o.Root = "/"
	}
	if o.Runner == nil {
		o.Runner = exec.NewRunner()
	}
	if o.Now == nil {
		o.Now = time.Now
	}
	if o.SocketPath == "" {
		o.SocketPath = filepath.Join(o.Root, config.SocketPath)
	}
	if o.Layout.Root == "" {
		o.Layout = install.Layout{Root: o.Root}
	}
	if o.Systemd == nil {
		o.Systemd = &systemd.Manager{Runner: o.Runner, Root: o.Root}
	}
	if o.SelfBinary == "" {
		o.SelfBinary = config.BinaryPath
	}
	if o.Mirror == "" {
		o.Mirror = os.Getenv(install.MirrorEnv)
	}
	if o.Arch == "" {
		o.Arch = runtime.GOARCH
	}
	if o.Notify == nil {
		o.Notify = systemd.Notify
	}
	if o.Getenv == nil {
		o.Getenv = os.Getenv
	}
	if o.Hooks == nil {
		o.Hooks = BackendHooks{Runner: o.Runner, Root: o.Root}
	}
	if o.Listen == nil {
		o.Listen = func(ctx context.Context, network, address string) (net.Listener, error) {
			var lc net.ListenConfig
			return lc.Listen(ctx, network, address)
		}
	}
	if o.LocalAddrs == nil {
		o.LocalAddrs = interfaceAddrs
	}
	if o.ListenPacket == nil {
		o.ListenPacket = func(ctx context.Context, network, address string) (net.PacketConn, error) {
			var lc net.ListenConfig
			return lc.ListenPacket(ctx, network, address)
		}
	}
	setDur(&o.HeartbeatInterval, api.HeartbeatInterval)
	setDur(&o.BackoffMin, api.ReconnectMin)
	setDur(&o.BackoffMax, api.ReconnectMax)
	setDur(&o.ReconnectDelay, DefaultReconnectDelay)
	setDur(&o.RestartDelay, DefaultRestartDelay)
	setDur(&o.UninstallDelay, DefaultUninstallDelay)
	setDur(&o.StartCheckDelay, DefaultStartCheckDelay)
	setDur(&o.FollowPoll, DefaultFollowPoll)
	setDur(&o.StallLimit, DefaultStallLimit)
	return o
}

func setDur(d *time.Duration, def time.Duration) {
	if *d <= 0 {
		*d = def
	}
}

// Run is `deyroute daemon node`: it loads Root/etc/deyroute/config.yaml (role
// node, DEY-X009 otherwise), keeps the control stream to the hub, executes
// the hub's commands, serves the Local API and returns nil once ctx ends and
// everything it started has stopped. It returns early with an error when
// the config cannot be loaded or the Local API socket cannot be served.
func Run(ctx context.Context, o Options) error {
	o = o.withDefaults()
	cfgPath := filepath.Join(o.Root, config.DefaultPath)
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return err
	}
	if cfg.Role != config.RoleNode || cfg.Node == nil {
		return deyerr.New(deyerr.X009, deyerr.Params{"role": cfg.Role, "need": config.RoleNode})
	}
	logger := o.Logger
	if logger == nil {
		l, closer, err := dlog.New(dlog.Options{Component: config.RoleNode, File: filepath.Join(o.Root, LogFile)})
		if err != nil {
			return err
		}
		defer func() { _ = closer.Close() }()
		logger = l
	}
	a := newAgent(o, cfg, cfgPath, logger)
	return a.run(ctx)
}

// snapshot is the latest measurement behind the heartbeat. unitsKnown is
// false until the first unit listing succeeded and after a failed one
// (units then holds the last list, if any).
type snapshot struct {
	units      map[string]string // unit → ActiveState
	unitsKnown bool
	cpu        float64
	ram        uint64
}

// agent is one running node agent.
type agent struct {
	o       Options
	log     *slog.Logger
	sd      *systemd.Manager
	writer  *render.HubWriter
	cfgPath string
	nodeID  string
	helloV  api.Hello

	ctx       context.Context // lifetime of Run
	jobs      sync.WaitGroup  // delayed background jobs (restart, uninstall, reconnect)
	jobsMu    sync.Mutex      // guards jobsDone against jobs.Add racing jobs.Wait
	jobsDone  bool            // Run is waiting for the jobs: no new ones
	reconnect chan struct{}
	listeners *registry
	cpu       cpuSampler
	// uninstalling is set by the first uninstall command; later ones are
	// answered without starting a second removal.
	uninstalling atomic.Bool
	// alive is the wall-clock time (UnixNano) the monitor last made
	// progress: the watchdog pings systemd only while it keeps running.
	alive atomic.Int64

	mu            sync.Mutex
	hubAddr       string
	front         config.NodeFront // node.front as last read; SecretFile != "" = front mode
	dialFail      *dialFailure     // the last failed attempt to open the front (nil = none)
	tlsCfg        *tls.Config
	connected     bool
	helloSeen     bool // the hub's hello arrived on the current connection
	lastContact   time.Time
	hubHello      *api.Hello
	lastError     string
	lastErrorCode deyerr.Code
	snap          snapshot

	instMu   sync.Mutex // serialises instance, unit and NAT changes
	st       nodeState
	started  map[string]bool
	pids     map[string]int // instance → MainPID seen after PostStart
	natApply []string       // last applied NAT rule set (nil = unknown)

	certMu sync.Mutex
	cfgMu  sync.Mutex // serialises changes of config.yaml
}

func newAgent(o Options, cfg *config.Config, cfgPath string, logger *slog.Logger) *agent {
	a := &agent{
		o:         o,
		log:       logger,
		sd:        o.Systemd,
		cfgPath:   cfgPath,
		nodeID:    cfg.Node.ID,
		hubAddr:   cfg.Node.HubAddr,
		front:     cfg.Node.Front,
		reconnect: make(chan struct{}, 1),
		listeners: newRegistry(),
		started:   map[string]bool{},
		pids:      map[string]int{},
		st:        nodeState{Instances: map[string]instance{}},
		ctx:       context.Background(),
	}
	a.writer = &render.HubWriter{Root: o.Root, Systemd: o.Systemd, Chown: o.Chown, DeyrouteIDs: o.DeyrouteIDs}
	a.helloV = api.Hello{
		NodeID:  a.nodeID,
		Version: version.Version,
		Arch:    o.Arch,
		OS:      osPrettyName(o.Root),
		Kernel:  readTrim(filepath.Join(o.Root, "/proc/sys/kernel/osrelease")),
		CPUs:    runtime.NumCPU(),
	}
	return a
}

// path joins an absolute system path with Root.
func (a *agent) path(p string) string { return filepath.Join(a.o.Root, p) }

func (a *agent) run(ctx context.Context) error {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	a.ctx = ctx
	a.loadState()
	a.cleanDownloads()
	a.registerFrontSecret()
	start := []any{dlog.Node(a.nodeID), slog.String("version", version.Version), slog.String("hub", a.hubAddress())}
	if a.frontMode() {
		start = append(start, slog.String("route", "front"))
	}
	a.log.Info("node agent starting", start...)

	var wg sync.WaitGroup
	localErr := make(chan error, 1)
	wg.Add(4)
	go func() {
		defer wg.Done()
		// Tunnel logs: copy-and-truncate rotation (section 12).
		dlog.RotateDirLoop(ctx, a.path(systemd.TunnelLogDir), dlog.RotateDirInterval, a.log)
	}()
	go func() {
		defer wg.Done()
		h := api.NewLocalHandler(a.localAPI(), a.log)
		localErr <- api.ServeLocalReady(ctx, a.o.SocketPath, h, a.log, func() {
			if err := a.o.Notify(systemd.StateReady); err != nil {
				a.log.Warn("sd_notify READY failed", dlog.Err(err))
			}
		})
	}()
	a.markAlive() // the stall limit counts from here, startup reconcile included
	go func() {
		defer wg.Done()
		a.watchdogLoop(ctx)
	}()
	go func() {
		defer wg.Done()
		// Know which instances run (and restore their NAT and the canary
		// echoes) before the hub can send commands; the Local API is already
		// served meanwhile.
		a.reconcile(ctx)
		a.restoreEchoes(ctx)
		var inner sync.WaitGroup
		inner.Add(2)
		go func() {
			defer inner.Done()
			a.monitorLoop(ctx)
		}()
		go func() {
			defer inner.Done()
			a.controlLoop(ctx)
		}()
		inner.Wait()
	}()

	var result error
	select {
	case <-ctx.Done():
	case err := <-localErr:
		if err != nil && ctx.Err() == nil {
			a.log.Error("local API stopped; the node agent exits", dlog.Err(err))
			result = err
		}
	}
	_ = a.o.Notify(systemd.StateStopping)
	cancel()
	wg.Wait()
	a.listeners.stopAll()
	a.jobsMu.Lock()
	a.jobsDone = true
	a.jobsMu.Unlock()
	a.jobs.Wait()
	a.log.Info("node agent stopped", dlog.Node(a.nodeID))
	return result
}

// markAlive records that the monitor made progress (watchdogLoop).
func (a *agent) markAlive() { a.alive.Store(time.Now().UnixNano()) }

// watchdogInterval is how often WATCHDOG=1 is due: half of $WATCHDOG_USEC,
// 0 when systemd runs no watchdog for this process (section 3: both
// services run with WatchdogSec).
func (a *agent) watchdogInterval() time.Duration {
	usec := strings.TrimSpace(a.o.Getenv("WATCHDOG_USEC"))
	if usec == "" {
		return 0
	}
	if pid := strings.TrimSpace(a.o.Getenv("WATCHDOG_PID")); pid != "" && pid != strconv.Itoa(os.Getpid()) {
		return 0
	}
	n, err := strconv.ParseInt(usec, 10, 64)
	if err != nil || n <= 0 {
		return 0
	}
	return time.Duration(n) * time.Microsecond / 2
}

// watchdogLoop sends WATCHDOG=1 every watchdog interval while the agent is
// responsive: the monitor (unit list, the agent and instance locks) must
// have made progress within StallLimit. An agent that hangs (a deadlocked
// lock, a stuck monitor) stops pinging and systemd restarts it; the tunnel
// units keep running meanwhile.
func (a *agent) watchdogLoop(ctx context.Context) {
	iv := a.watchdogInterval()
	if iv <= 0 {
		return
	}
	stale := max(a.o.StallLimit, 3*a.o.HeartbeatInterval)
	t := time.NewTicker(iv)
	defer t.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-t.C:
		}
		if since := time.Since(time.Unix(0, a.alive.Load())); since > stale {
			a.log.Error("node agent is not responsive; the watchdog ping is withheld so systemd restarts it",
				slog.Duration("stalled", since.Round(time.Second)), dlog.Code(deyerr.X000))
			continue
		}
		if err := a.o.Notify(systemd.StateWatchdog); err != nil {
			a.log.Warn("watchdog notification failed", dlog.Err(err))
		}
	}
}

// controlLoop keeps one api.ControlClient running with the current
// credentials; a reconnect request (set_hub, cert.install) replaces it.
func (a *agent) controlLoop(ctx context.Context) {
	for {
		cfg, err := a.loadTLS()
		if err != nil {
			a.setLastError(err)
			a.log.Error("cannot load the node certificate; retrying", dlog.Err(err), dlog.Code(deyerr.As(err).Code))
			t := time.NewTimer(a.o.BackoffMax)
			select {
			case <-ctx.Done():
				t.Stop()
				return
			case <-a.reconnect:
				t.Stop()
			case <-t.C:
			}
			continue
		}
		a.mu.Lock()
		a.tlsCfg = cfg
		a.mu.Unlock()
		client := a.controlClient(cfg)
		cctx, ccancel := context.WithCancel(ctx)
		done := make(chan struct{})
		go func() {
			defer close(done)
			if err := client.Run(cctx); err != nil {
				a.log.Error("control client stopped", dlog.Err(err))
			}
		}()
		select {
		case <-ctx.Done():
			ccancel()
			<-done
			return
		case <-a.reconnect:
			a.log.Info("reconnecting to the hub with the current address and credentials")
			ccancel()
			<-done
		}
	}
}

// controlClient returns a client for the current credentials. The same
// shape is used for uploads and asset downloads.
func (a *agent) controlClient(cfg *tls.Config) *api.ControlClient {
	c := &api.ControlClient{
		AddrFunc:          a.hubAddress,
		TLSConfig:         cfg,
		Hello:             a.hello,
		Heartbeat:         a.heartbeat,
		Handler:           a.handle,
		Logger:            a.log,
		OnConnected:       a.onConnected,
		OnDisconnected:    a.onDisconnected,
		OnHubHello:        a.onHubHello,
		BackoffMin:        a.o.BackoffMin,
		BackoffMax:        a.o.BackoffMax,
		HeartbeatInterval: a.o.HeartbeatInterval,
	}
	a.applyFront(c)
	return c
}

// requestClient is a client for one-off requests (upload, asset) with the
// credentials of the running stream.
func (a *agent) requestClient() (*api.ControlClient, error) {
	a.mu.Lock()
	cfg := a.tlsCfg
	a.mu.Unlock()
	if cfg == nil {
		var err error
		if cfg, err = a.loadTLS(); err != nil {
			return nil, err
		}
	}
	c := &api.ControlClient{AddrFunc: a.hubAddress, TLSConfig: cfg, Hello: a.hello, Logger: a.log}
	a.applyFront(c)
	return c, nil
}

// loadTLS builds the control channel TLS config from ca.crt and the node
// certificate and key named in config.yaml.
func (a *agent) loadTLS() (*tls.Config, error) {
	cfg, err := config.Load(a.cfgPath)
	if err != nil {
		return nil, err
	}
	if cfg.Node == nil {
		return nil, deyerr.New(deyerr.C016, deyerr.Params{"role": cfg.Role})
	}
	read := func(p string) ([]byte, error) {
		data, err := os.ReadFile(a.path(p)) // #nosec G304 -- paths from config.yaml below Root
		if err != nil {
			return nil, deyerr.Wrap(deyerr.T008, err, deyerr.Params{"path": p, "reason": err.Error()})
		}
		return data, nil
	}
	caPEM, err := read(CAFile)
	if err != nil {
		return nil, err
	}
	certPEM, err := read(cfg.Node.CertFile)
	if err != nil {
		return nil, err
	}
	keyPEM, err := read(cfg.Node.KeyFile)
	if err != nil {
		return nil, err
	}
	dlog.RegisterSecret(strings.TrimSpace(string(keyPEM)))
	tc, err := tlsutil.ClientTLSConfig(caPEM, certPEM, keyPEM, "")
	if err != nil {
		return nil, err
	}
	tlsutil.SetCoverSNI(tc, cfg.Node.ControlSNI)
	return tc, nil
}

// hubAddress returns the hub control address: the override, else
// node.hub_addr as currently stored in config.yaml (so set-hub takes effect
// on the next reconnect), else the last known value.
func (a *agent) hubAddress() string {
	if a.o.HubAddrOverride != "" {
		return a.o.HubAddrOverride
	}
	cfg, err := config.Load(a.cfgPath)
	a.mu.Lock()
	defer a.mu.Unlock()
	if err == nil && cfg.Node != nil && cfg.Node.HubAddr != "" {
		a.hubAddr = cfg.Node.HubAddr
	}
	return a.hubAddr
}

// requestReconnect drops the control stream after delay; the control loop
// then reconnects with the current address and credentials.
func (a *agent) requestReconnect(delay time.Duration) {
	a.later(delay, func(context.Context) error {
		select {
		case a.reconnect <- struct{}{}:
		default:
		}
		return nil
	})
}

// later runs fn after delay in the background unless the agent stops
// first. Once started fn is not cancelled by the agent stopping (it may be
// what stops it: restart, uninstall); it gets DefaultJobTimeout instead.
// A job asked for while Run already waits for the jobs (a Local API
// handler that outlived the shutdown) is dropped.
func (a *agent) later(delay time.Duration, fn func(ctx context.Context) error) {
	a.jobsMu.Lock()
	if a.jobsDone {
		a.jobsMu.Unlock()
		return
	}
	a.jobs.Add(1)
	a.jobsMu.Unlock()
	go func() {
		defer a.jobs.Done()
		t := time.NewTimer(delay)
		defer t.Stop()
		select {
		case <-a.ctx.Done():
			return
		case <-t.C:
		}
		ctx, cancel := context.WithTimeout(context.WithoutCancel(a.ctx), DefaultJobTimeout)
		defer cancel()
		if err := fn(ctx); err != nil {
			a.setLastError(err)
			a.log.Error("background job failed", dlog.Err(err), dlog.Code(deyerr.As(err).Code))
		}
	}()
}

func (a *agent) hello() api.Hello { return a.helloV }

// heartbeat returns the latest measurements; it is called by the control
// client every heartbeat interval while the stream is up, the first time
// as soon as it opened. Until the monitor listed the units (systemctl may
// be slow after a boot or an update restart) the beat says so
// (UnitsUnknown): the hub's per-stream cleanup must not take an empty list
// for "nothing runs".
func (a *agent) heartbeat() api.Heartbeat {
	now := a.o.Now().UTC()
	a.mu.Lock()
	defer a.mu.Unlock()
	a.lastContact = now
	units := make(map[string]string, len(a.snap.units))
	for k, v := range a.snap.units {
		units[k] = v
	}
	return api.Heartbeat{At: now, CPUPercent: a.snap.cpu, RAMBytes: a.snap.ram, Units: units,
		UnitsUnknown: !a.snap.unitsKnown, LastError: a.lastError}
}

func (a *agent) onConnected() {
	a.mu.Lock()
	a.connected = true
	a.helloSeen = false
	a.lastContact = a.o.Now().UTC()
	a.mu.Unlock()
}

func (a *agent) onDisconnected() {
	a.mu.Lock()
	a.connected = false
	a.helloSeen = false
	a.mu.Unlock()
}

func (a *agent) onHubHello(h api.Hello) {
	a.mu.Lock()
	a.hubHello = &h
	a.helloSeen = true
	a.lastContact = a.o.Now().UTC()
	a.mu.Unlock()
	if !h.Compatible {
		err := deyerr.New(deyerr.N004, deyerr.Params{"node": a.nodeID, "node_version": version.Version, "hub_version": h.Version})
		a.setLastError(err)
		a.log.Warn("hub reports an incompatible version; commands are refused until this node is updated",
			slog.String("hub_version", h.Version), dlog.Code(deyerr.N004))
		return
	}
	// A compatible hub ends an earlier incompatibility: the heartbeat must
	// not keep reporting it.
	a.mu.Lock()
	if a.lastErrorCode == deyerr.N004 {
		a.lastError, a.lastErrorCode = "", ""
	}
	a.mu.Unlock()
}

// touch records contact with the hub (a command arrived).
func (a *agent) touch() {
	a.mu.Lock()
	a.lastContact = a.o.Now().UTC()
	a.mu.Unlock()
}

// setLastError keeps the latest failure for the heartbeat ("DEY-X000
// message", redacted).
func (a *agent) setLastError(err error) {
	if err == nil {
		return
	}
	e := deyerr.As(err)
	msg := dlog.Redact(string(e.Code) + " " + e.Message())
	a.mu.Lock()
	a.lastError, a.lastErrorCode = msg, e.Code
	a.mu.Unlock()
}
