// Code generated by internal/api/gen from local.go; DO NOT EDIT.

package apitest

import (
	"context"
	"time"

	"github.com/localroot4/deyroute/internal/api"
	"github.com/localroot4/deyroute/internal/state"
)

// Stub implements api.Local with one optional function per method, for
// CLI and TUI tests. A method whose function is nil returns DEY-X008.
type Stub struct {
	// StatusFn implements Status.
	StatusFn func(ctx context.Context) (api.Status, error)
	// EventsFn implements Events.
	EventsFn func(ctx context.Context, q api.EventQuery) ([]state.Event, error)
	// LogsFn implements Logs.
	LogsFn func(ctx context.Context, q api.LogQuery, emit func(api.LogLine) error) error
	// ConfigApplyFn implements ConfigApply.
	ConfigApplyFn func(ctx context.Context, progress func(api.Step)) (api.ApplyResult, error)
	// SettingsSetFn implements SettingsSet.
	SettingsSetFn func(ctx context.Context, req api.SettingsRequest) error
	// NodeJoinCommandFn implements NodeJoinCommand.
	NodeJoinCommandFn func(ctx context.Context, ttl time.Duration) (api.JoinCommand, error)
	// NodeListFn implements NodeList.
	NodeListFn func(ctx context.Context) ([]api.NodeInfo, error)
	// NodeRenameFn implements NodeRename.
	NodeRenameFn func(ctx context.Context, id string, name string) error
	// NodeRemoveFn implements NodeRemove.
	NodeRemoveFn func(ctx context.Context, id string) error
	// NodeTestFn implements NodeTest.
	NodeTestFn func(ctx context.Context, id string) (api.NodeTestResult, error)
	// HubAnnounceMoveFn implements HubAnnounceMove.
	HubAnnounceMoveFn func(ctx context.Context, newAddr string) (api.AnnounceResult, error)
	// NodeSetHubFn implements NodeSetHub.
	NodeSetHubFn func(ctx context.Context, addr string) error
	// TunnelAddFn implements TunnelAdd.
	TunnelAddFn func(ctx context.Context, req api.TunnelAddRequest, progress func(api.Step)) (api.TunnelInfo, error)
	// TunnelListFn implements TunnelList.
	TunnelListFn func(ctx context.Context) ([]api.TunnelInfo, error)
	// TunnelShowFn implements TunnelShow.
	TunnelShowFn func(ctx context.Context, id string) (api.TunnelDetail, error)
	// TunnelEditFn implements TunnelEdit.
	TunnelEditFn func(ctx context.Context, id string, req api.TunnelEditRequest, progress func(api.Step)) (api.TunnelInfo, error)
	// TunnelSetEnabledFn implements TunnelSetEnabled.
	TunnelSetEnabledFn func(ctx context.Context, id string, enabled bool) error
	// TunnelRestartFn implements TunnelRestart.
	TunnelRestartFn func(ctx context.Context, id string) error
	// TunnelDeleteFn implements TunnelDelete.
	TunnelDeleteFn func(ctx context.Context, id string, progress func(api.Step)) error
	// TunnelSwitchFn implements TunnelSwitch.
	TunnelSwitchFn func(ctx context.Context, id string, req api.SwitchRequest) error
	// TunnelResetFn implements TunnelReset.
	TunnelResetFn func(ctx context.Context, id string) error
	// TunnelPauseFn implements TunnelPause.
	TunnelPauseFn func(ctx context.Context, id string) error
	// TunnelResumeFn implements TunnelResume.
	TunnelResumeFn func(ctx context.Context, id string) error
	// TunnelTestLadderFn implements TunnelTestLadder.
	TunnelTestLadderFn func(ctx context.Context, id string, progress func(api.Step)) ([]api.RungResult, error)
	// TunnelBackupAddFn implements TunnelBackupAdd.
	TunnelBackupAddFn func(ctx context.Context, id string, node string, progress func(api.Step)) error
	// TunnelBackupRemoveFn implements TunnelBackupRemove.
	TunnelBackupRemoveFn func(ctx context.Context, id string, node string) error
	// PortAddFn implements PortAdd.
	PortAddFn func(ctx context.Context, tunnel string, specs []api.PortSpec, progress func(api.Step)) (api.TunnelInfo, error)
	// PortRemoveFn implements PortRemove.
	PortRemoveFn func(ctx context.Context, tunnel string, listen int, proto string) (api.TunnelInfo, error)
	// PortCheckFn implements PortCheck.
	PortCheckFn func(ctx context.Context, req api.PortCheckRequest) (api.PortCheckResult, error)
	// PortSuggestFn implements PortSuggest.
	PortSuggestFn func(ctx context.Context, count int) ([]int, error)
	// LadderListFn implements LadderList.
	LadderListFn func(ctx context.Context) ([]api.Ladder, error)
	// LadderSaveFn implements LadderSave.
	LadderSaveFn func(ctx context.Context, name string, rungs []string, create bool) error
	// LadderDeleteFn implements LadderDelete.
	LadderDeleteFn func(ctx context.Context, name string) error
	// TransportListFn implements TransportList.
	TransportListFn func(ctx context.Context) ([]api.TransportInfo, error)
	// DiagSpeedFn implements DiagSpeed.
	DiagSpeedFn func(ctx context.Context, tunnel string, seconds int, progress func(api.Step)) (api.SpeedResult, error)
	// DiagProbeFn implements DiagProbe.
	DiagProbeFn func(ctx context.Context, tunnel string, allPorts bool) ([]api.ProbeReport, error)
	// DoctorCollectFn implements DoctorCollect.
	DoctorCollectFn func(ctx context.Context, node string) (api.DoctorData, error)
	// OptimizeStatusFn implements OptimizeStatus.
	OptimizeStatusFn func(ctx context.Context) (api.OptimizeStatus, error)
	// OptimizeApplyFn implements OptimizeApply.
	OptimizeApplyFn func(ctx context.Context, profile string) (api.OptimizeStatus, error)
	// OptimizeRevertFn implements OptimizeRevert.
	OptimizeRevertFn func(ctx context.Context) (api.OptimizeStatus, error)
	// SecurityRotateTokensFn implements SecurityRotateTokens.
	SecurityRotateTokensFn func(ctx context.Context, tunnel string, progress func(api.Step)) error
	// SecurityRotateCAFn implements SecurityRotateCA.
	SecurityRotateCAFn func(ctx context.Context, progress func(api.Step)) (api.RotateCAResult, error)
	// SecurityTLSShowFn implements SecurityTLSShow.
	SecurityTLSShowFn func(ctx context.Context, tunnel string) ([]api.CertInfo, error)
	// SecurityTLSRenewFn implements SecurityTLSRenew.
	SecurityTLSRenewFn func(ctx context.Context, tunnel string) ([]api.CertInfo, error)
	// SecurityFirewallFn implements SecurityFirewall.
	SecurityFirewallFn func(ctx context.Context, action string) (api.FirewallInfo, error)
	// SecurityAuditFn implements SecurityAudit.
	SecurityAuditFn func(ctx context.Context) (api.AuditReport, error)
	// NotifyTelegramSetFn implements NotifyTelegramSet.
	NotifyTelegramSetFn func(ctx context.Context, tokenFile string, chatID string, events []string) error
	// NotifyTelegramTestFn implements NotifyTelegramTest.
	NotifyTelegramTestFn func(ctx context.Context) error
	// NotifyTelegramOffFn implements NotifyTelegramOff.
	NotifyTelegramOffFn func(ctx context.Context) error
	// UpdateCheckFn implements UpdateCheck.
	UpdateCheckFn func(ctx context.Context) (api.UpdateInfo, error)
	// UpdateApplyFn implements UpdateApply.
	UpdateApplyFn func(ctx context.Context, version string, progress func(api.Step)) (api.UpdateInfo, error)
	// UpdateRollbackFn implements UpdateRollback.
	UpdateRollbackFn func(ctx context.Context) (api.UpdateInfo, error)
	// UpdateBackendsFn implements UpdateBackends.
	UpdateBackendsFn func(ctx context.Context, name string, progress func(api.Step)) ([]api.BackendUpdate, error)
	// UpdateManifestFn implements UpdateManifest.
	UpdateManifestFn func(ctx context.Context) (api.ManifestInfo, error)
	// UninstallNodesFn implements UninstallNodes.
	UninstallNodesFn func(ctx context.Context) ([]string, error)
	// StopAllFn implements StopAll.
	StopAllFn func(ctx context.Context) error
}

// Compile-time check that Stub implements api.Local.
var _ api.Local = (*Stub)(nil)

// Status calls StatusFn or returns DEY-X008 when it is nil.
func (s *Stub) Status(ctx context.Context) (api.Status, error) {
	if s.StatusFn == nil {
		var zero api.Status
		return zero, notImplemented("Status")
	}
	return s.StatusFn(ctx)
}

// Events calls EventsFn or returns DEY-X008 when it is nil.
func (s *Stub) Events(ctx context.Context, q api.EventQuery) ([]state.Event, error) {
	if s.EventsFn == nil {
		var zero []state.Event
		return zero, notImplemented("Events")
	}
	return s.EventsFn(ctx, q)
}

// Logs calls LogsFn or returns DEY-X008 when it is nil.
func (s *Stub) Logs(ctx context.Context, q api.LogQuery, emit func(api.LogLine) error) error {
	if s.LogsFn == nil {
		return notImplemented("Logs")
	}
	return s.LogsFn(ctx, q, emit)
}

// ConfigApply calls ConfigApplyFn or returns DEY-X008 when it is nil.
func (s *Stub) ConfigApply(ctx context.Context, progress func(api.Step)) (api.ApplyResult, error) {
	if s.ConfigApplyFn == nil {
		var zero api.ApplyResult
		return zero, notImplemented("ConfigApply")
	}
	return s.ConfigApplyFn(ctx, progress)
}

// SettingsSet calls SettingsSetFn or returns DEY-X008 when it is nil.
func (s *Stub) SettingsSet(ctx context.Context, req api.SettingsRequest) error {
	if s.SettingsSetFn == nil {
		return notImplemented("SettingsSet")
	}
	return s.SettingsSetFn(ctx, req)
}

// NodeJoinCommand calls NodeJoinCommandFn or returns DEY-X008 when it is nil.
func (s *Stub) NodeJoinCommand(ctx context.Context, ttl time.Duration) (api.JoinCommand, error) {
	if s.NodeJoinCommandFn == nil {
		var zero api.JoinCommand
		return zero, notImplemented("NodeJoinCommand")
	}
	return s.NodeJoinCommandFn(ctx, ttl)
}

// NodeList calls NodeListFn or returns DEY-X008 when it is nil.
func (s *Stub) NodeList(ctx context.Context) ([]api.NodeInfo, error) {
	if s.NodeListFn == nil {
		var zero []api.NodeInfo
		return zero, notImplemented("NodeList")
	}
	return s.NodeListFn(ctx)
}

// NodeRename calls NodeRenameFn or returns DEY-X008 when it is nil.
func (s *Stub) NodeRename(ctx context.Context, id string, name string) error {
	if s.NodeRenameFn == nil {
		return notImplemented("NodeRename")
	}
	return s.NodeRenameFn(ctx, id, name)
}

// NodeRemove calls NodeRemoveFn or returns DEY-X008 when it is nil.
func (s *Stub) NodeRemove(ctx context.Context, id string) error {
	if s.NodeRemoveFn == nil {
		return notImplemented("NodeRemove")
	}
	return s.NodeRemoveFn(ctx, id)
}

// NodeTest calls NodeTestFn or returns DEY-X008 when it is nil.
func (s *Stub) NodeTest(ctx context.Context, id string) (api.NodeTestResult, error) {
	if s.NodeTestFn == nil {
		var zero api.NodeTestResult
		return zero, notImplemented("NodeTest")
	}
	return s.NodeTestFn(ctx, id)
}

// HubAnnounceMove calls HubAnnounceMoveFn or returns DEY-X008 when it is nil.
func (s *Stub) HubAnnounceMove(ctx context.Context, newAddr string) (api.AnnounceResult, error) {
	if s.HubAnnounceMoveFn == nil {
		var zero api.AnnounceResult
		return zero, notImplemented("HubAnnounceMove")
	}
	return s.HubAnnounceMoveFn(ctx, newAddr)
}

// NodeSetHub calls NodeSetHubFn or returns DEY-X008 when it is nil.
func (s *Stub) NodeSetHub(ctx context.Context, addr string) error {
	if s.NodeSetHubFn == nil {
		return notImplemented("NodeSetHub")
	}
	return s.NodeSetHubFn(ctx, addr)
}

// TunnelAdd calls TunnelAddFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelAdd(ctx context.Context, req api.TunnelAddRequest, progress func(api.Step)) (api.TunnelInfo, error) {
	if s.TunnelAddFn == nil {
		var zero api.TunnelInfo
		return zero, notImplemented("TunnelAdd")
	}
	return s.TunnelAddFn(ctx, req, progress)
}

// TunnelList calls TunnelListFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelList(ctx context.Context) ([]api.TunnelInfo, error) {
	if s.TunnelListFn == nil {
		var zero []api.TunnelInfo
		return zero, notImplemented("TunnelList")
	}
	return s.TunnelListFn(ctx)
}

// TunnelShow calls TunnelShowFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelShow(ctx context.Context, id string) (api.TunnelDetail, error) {
	if s.TunnelShowFn == nil {
		var zero api.TunnelDetail
		return zero, notImplemented("TunnelShow")
	}
	return s.TunnelShowFn(ctx, id)
}

// TunnelEdit calls TunnelEditFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelEdit(ctx context.Context, id string, req api.TunnelEditRequest, progress func(api.Step)) (api.TunnelInfo, error) {
	if s.TunnelEditFn == nil {
		var zero api.TunnelInfo
		return zero, notImplemented("TunnelEdit")
	}
	return s.TunnelEditFn(ctx, id, req, progress)
}

// TunnelSetEnabled calls TunnelSetEnabledFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelSetEnabled(ctx context.Context, id string, enabled bool) error {
	if s.TunnelSetEnabledFn == nil {
		return notImplemented("TunnelSetEnabled")
	}
	return s.TunnelSetEnabledFn(ctx, id, enabled)
}

// TunnelRestart calls TunnelRestartFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelRestart(ctx context.Context, id string) error {
	if s.TunnelRestartFn == nil {
		return notImplemented("TunnelRestart")
	}
	return s.TunnelRestartFn(ctx, id)
}

// TunnelDelete calls TunnelDeleteFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelDelete(ctx context.Context, id string, progress func(api.Step)) error {
	if s.TunnelDeleteFn == nil {
		return notImplemented("TunnelDelete")
	}
	return s.TunnelDeleteFn(ctx, id, progress)
}

// TunnelSwitch calls TunnelSwitchFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelSwitch(ctx context.Context, id string, req api.SwitchRequest) error {
	if s.TunnelSwitchFn == nil {
		return notImplemented("TunnelSwitch")
	}
	return s.TunnelSwitchFn(ctx, id, req)
}

// TunnelReset calls TunnelResetFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelReset(ctx context.Context, id string) error {
	if s.TunnelResetFn == nil {
		return notImplemented("TunnelReset")
	}
	return s.TunnelResetFn(ctx, id)
}

// TunnelPause calls TunnelPauseFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelPause(ctx context.Context, id string) error {
	if s.TunnelPauseFn == nil {
		return notImplemented("TunnelPause")
	}
	return s.TunnelPauseFn(ctx, id)
}

// TunnelResume calls TunnelResumeFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelResume(ctx context.Context, id string) error {
	if s.TunnelResumeFn == nil {
		return notImplemented("TunnelResume")
	}
	return s.TunnelResumeFn(ctx, id)
}

// TunnelTestLadder calls TunnelTestLadderFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelTestLadder(ctx context.Context, id string, progress func(api.Step)) ([]api.RungResult, error) {
	if s.TunnelTestLadderFn == nil {
		var zero []api.RungResult
		return zero, notImplemented("TunnelTestLadder")
	}
	return s.TunnelTestLadderFn(ctx, id, progress)
}

// TunnelBackupAdd calls TunnelBackupAddFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelBackupAdd(ctx context.Context, id string, node string, progress func(api.Step)) error {
	if s.TunnelBackupAddFn == nil {
		return notImplemented("TunnelBackupAdd")
	}
	return s.TunnelBackupAddFn(ctx, id, node, progress)
}

// TunnelBackupRemove calls TunnelBackupRemoveFn or returns DEY-X008 when it is nil.
func (s *Stub) TunnelBackupRemove(ctx context.Context, id string, node string) error {
	if s.TunnelBackupRemoveFn == nil {
		return notImplemented("TunnelBackupRemove")
	}
	return s.TunnelBackupRemoveFn(ctx, id, node)
}

// PortAdd calls PortAddFn or returns DEY-X008 when it is nil.
func (s *Stub) PortAdd(ctx context.Context, tunnel string, specs []api.PortSpec, progress func(api.Step)) (api.TunnelInfo, error) {
	if s.PortAddFn == nil {
		var zero api.TunnelInfo
		return zero, notImplemented("PortAdd")
	}
	return s.PortAddFn(ctx, tunnel, specs, progress)
}

// PortRemove calls PortRemoveFn or returns DEY-X008 when it is nil.
func (s *Stub) PortRemove(ctx context.Context, tunnel string, listen int, proto string) (api.TunnelInfo, error) {
	if s.PortRemoveFn == nil {
		var zero api.TunnelInfo
		return zero, notImplemented("PortRemove")
	}
	return s.PortRemoveFn(ctx, tunnel, listen, proto)
}

// PortCheck calls PortCheckFn or returns DEY-X008 when it is nil.
func (s *Stub) PortCheck(ctx context.Context, req api.PortCheckRequest) (api.PortCheckResult, error) {
	if s.PortCheckFn == nil {
		var zero api.PortCheckResult
		return zero, notImplemented("PortCheck")
	}
	return s.PortCheckFn(ctx, req)
}

// PortSuggest calls PortSuggestFn or returns DEY-X008 when it is nil.
func (s *Stub) PortSuggest(ctx context.Context, count int) ([]int, error) {
	if s.PortSuggestFn == nil {
		var zero []int
		return zero, notImplemented("PortSuggest")
	}
	return s.PortSuggestFn(ctx, count)
}

// LadderList calls LadderListFn or returns DEY-X008 when it is nil.
func (s *Stub) LadderList(ctx context.Context) ([]api.Ladder, error) {
	if s.LadderListFn == nil {
		var zero []api.Ladder
		return zero, notImplemented("LadderList")
	}
	return s.LadderListFn(ctx)
}

// LadderSave calls LadderSaveFn or returns DEY-X008 when it is nil.
func (s *Stub) LadderSave(ctx context.Context, name string, rungs []string, create bool) error {
	if s.LadderSaveFn == nil {
		return notImplemented("LadderSave")
	}
	return s.LadderSaveFn(ctx, name, rungs, create)
}

// LadderDelete calls LadderDeleteFn or returns DEY-X008 when it is nil.
func (s *Stub) LadderDelete(ctx context.Context, name string) error {
	if s.LadderDeleteFn == nil {
		return notImplemented("LadderDelete")
	}
	return s.LadderDeleteFn(ctx, name)
}

// TransportList calls TransportListFn or returns DEY-X008 when it is nil.
func (s *Stub) TransportList(ctx context.Context) ([]api.TransportInfo, error) {
	if s.TransportListFn == nil {
		var zero []api.TransportInfo
		return zero, notImplemented("TransportList")
	}
	return s.TransportListFn(ctx)
}

// DiagSpeed calls DiagSpeedFn or returns DEY-X008 when it is nil.
func (s *Stub) DiagSpeed(ctx context.Context, tunnel string, seconds int, progress func(api.Step)) (api.SpeedResult, error) {
	if s.DiagSpeedFn == nil {
		var zero api.SpeedResult
		return zero, notImplemented("DiagSpeed")
	}
	return s.DiagSpeedFn(ctx, tunnel, seconds, progress)
}

// DiagProbe calls DiagProbeFn or returns DEY-X008 when it is nil.
func (s *Stub) DiagProbe(ctx context.Context, tunnel string, allPorts bool) ([]api.ProbeReport, error) {
	if s.DiagProbeFn == nil {
		var zero []api.ProbeReport
		return zero, notImplemented("DiagProbe")
	}
	return s.DiagProbeFn(ctx, tunnel, allPorts)
}

// DoctorCollect calls DoctorCollectFn or returns DEY-X008 when it is nil.
func (s *Stub) DoctorCollect(ctx context.Context, node string) (api.DoctorData, error) {
	if s.DoctorCollectFn == nil {
		var zero api.DoctorData
		return zero, notImplemented("DoctorCollect")
	}
	return s.DoctorCollectFn(ctx, node)
}

// OptimizeStatus calls OptimizeStatusFn or returns DEY-X008 when it is nil.
func (s *Stub) OptimizeStatus(ctx context.Context) (api.OptimizeStatus, error) {
	if s.OptimizeStatusFn == nil {
		var zero api.OptimizeStatus
		return zero, notImplemented("OptimizeStatus")
	}
	return s.OptimizeStatusFn(ctx)
}

// OptimizeApply calls OptimizeApplyFn or returns DEY-X008 when it is nil.
func (s *Stub) OptimizeApply(ctx context.Context, profile string) (api.OptimizeStatus, error) {
	if s.OptimizeApplyFn == nil {
		var zero api.OptimizeStatus
		return zero, notImplemented("OptimizeApply")
	}
	return s.OptimizeApplyFn(ctx, profile)
}

// OptimizeRevert calls OptimizeRevertFn or returns DEY-X008 when it is nil.
func (s *Stub) OptimizeRevert(ctx context.Context) (api.OptimizeStatus, error) {
	if s.OptimizeRevertFn == nil {
		var zero api.OptimizeStatus
		return zero, notImplemented("OptimizeRevert")
	}
	return s.OptimizeRevertFn(ctx)
}

// SecurityRotateTokens calls SecurityRotateTokensFn or returns DEY-X008 when it is nil.
func (s *Stub) SecurityRotateTokens(ctx context.Context, tunnel string, progress func(api.Step)) error {
	if s.SecurityRotateTokensFn == nil {
		return notImplemented("SecurityRotateTokens")
	}
	return s.SecurityRotateTokensFn(ctx, tunnel, progress)
}

// SecurityRotateCA calls SecurityRotateCAFn or returns DEY-X008 when it is nil.
func (s *Stub) SecurityRotateCA(ctx context.Context, progress func(api.Step)) (api.RotateCAResult, error) {
	if s.SecurityRotateCAFn == nil {
		var zero api.RotateCAResult
		return zero, notImplemented("SecurityRotateCA")
	}
	return s.SecurityRotateCAFn(ctx, progress)
}

// SecurityTLSShow calls SecurityTLSShowFn or returns DEY-X008 when it is nil.
func (s *Stub) SecurityTLSShow(ctx context.Context, tunnel string) ([]api.CertInfo, error) {
	if s.SecurityTLSShowFn == nil {
		var zero []api.CertInfo
		return zero, notImplemented("SecurityTLSShow")
	}
	return s.SecurityTLSShowFn(ctx, tunnel)
}

// SecurityTLSRenew calls SecurityTLSRenewFn or returns DEY-X008 when it is nil.
func (s *Stub) SecurityTLSRenew(ctx context.Context, tunnel string) ([]api.CertInfo, error) {
	if s.SecurityTLSRenewFn == nil {
		var zero []api.CertInfo
		return zero, notImplemented("SecurityTLSRenew")
	}
	return s.SecurityTLSRenewFn(ctx, tunnel)
}

// SecurityFirewall calls SecurityFirewallFn or returns DEY-X008 when it is nil.
func (s *Stub) SecurityFirewall(ctx context.Context, action string) (api.FirewallInfo, error) {
	if s.SecurityFirewallFn == nil {
		var zero api.FirewallInfo
		return zero, notImplemented("SecurityFirewall")
	}
	return s.SecurityFirewallFn(ctx, action)
}

// SecurityAudit calls SecurityAuditFn or returns DEY-X008 when it is nil.
func (s *Stub) SecurityAudit(ctx context.Context) (api.AuditReport, error) {
	if s.SecurityAuditFn == nil {
		var zero api.AuditReport
		return zero, notImplemented("SecurityAudit")
	}
	return s.SecurityAuditFn(ctx)
}

// NotifyTelegramSet calls NotifyTelegramSetFn or returns DEY-X008 when it is nil.
func (s *Stub) NotifyTelegramSet(ctx context.Context, tokenFile string, chatID string, events []string) error {
	if s.NotifyTelegramSetFn == nil {
		return notImplemented("NotifyTelegramSet")
	}
	return s.NotifyTelegramSetFn(ctx, tokenFile, chatID, events)
}

// NotifyTelegramTest calls NotifyTelegramTestFn or returns DEY-X008 when it is nil.
func (s *Stub) NotifyTelegramTest(ctx context.Context) error {
	if s.NotifyTelegramTestFn == nil {
		return notImplemented("NotifyTelegramTest")
	}
	return s.NotifyTelegramTestFn(ctx)
}

// NotifyTelegramOff calls NotifyTelegramOffFn or returns DEY-X008 when it is nil.
func (s *Stub) NotifyTelegramOff(ctx context.Context) error {
	if s.NotifyTelegramOffFn == nil {
		return notImplemented("NotifyTelegramOff")
	}
	return s.NotifyTelegramOffFn(ctx)
}

// UpdateCheck calls UpdateCheckFn or returns DEY-X008 when it is nil.
func (s *Stub) UpdateCheck(ctx context.Context) (api.UpdateInfo, error) {
	if s.UpdateCheckFn == nil {
		var zero api.UpdateInfo
		return zero, notImplemented("UpdateCheck")
	}
	return s.UpdateCheckFn(ctx)
}

// UpdateApply calls UpdateApplyFn or returns DEY-X008 when it is nil.
func (s *Stub) UpdateApply(ctx context.Context, version string, progress func(api.Step)) (api.UpdateInfo, error) {
	if s.UpdateApplyFn == nil {
		var zero api.UpdateInfo
		return zero, notImplemented("UpdateApply")
	}
	return s.UpdateApplyFn(ctx, version, progress)
}

// UpdateRollback calls UpdateRollbackFn or returns DEY-X008 when it is nil.
func (s *Stub) UpdateRollback(ctx context.Context) (api.UpdateInfo, error) {
	if s.UpdateRollbackFn == nil {
		var zero api.UpdateInfo
		return zero, notImplemented("UpdateRollback")
	}
	return s.UpdateRollbackFn(ctx)
}

// UpdateBackends calls UpdateBackendsFn or returns DEY-X008 when it is nil.
func (s *Stub) UpdateBackends(ctx context.Context, name string, progress func(api.Step)) ([]api.BackendUpdate, error) {
	if s.UpdateBackendsFn == nil {
		var zero []api.BackendUpdate
		return zero, notImplemented("UpdateBackends")
	}
	return s.UpdateBackendsFn(ctx, name, progress)
}

// UpdateManifest calls UpdateManifestFn or returns DEY-X008 when it is nil.
func (s *Stub) UpdateManifest(ctx context.Context) (api.ManifestInfo, error) {
	if s.UpdateManifestFn == nil {
		var zero api.ManifestInfo
		return zero, notImplemented("UpdateManifest")
	}
	return s.UpdateManifestFn(ctx)
}

// UninstallNodes calls UninstallNodesFn or returns DEY-X008 when it is nil.
func (s *Stub) UninstallNodes(ctx context.Context) ([]string, error) {
	if s.UninstallNodesFn == nil {
		var zero []string
		return zero, notImplemented("UninstallNodes")
	}
	return s.UninstallNodesFn(ctx)
}

// StopAll calls StopAllFn or returns DEY-X008 when it is nil.
func (s *Stub) StopAll(ctx context.Context) error {
	if s.StopAllFn == nil {
		return notImplemented("StopAll")
	}
	return s.StopAllFn(ctx)
}
